[a_size_shift.full_rmse.bayesian]
smax = 1.0
smin = -1.0

[a_size_shift.mae.bayesian]
smax = 1.0
smin = -1.0

[a_size_distortion.full_rmse.bayesian]
smax = 1.0
smin = -0.9643978113442981

[a_size_outlier.full_rmse.bayesian]
smax = 1.0
smin = -1.0
