# Generated by Django 3.1 on 2022-11-22 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OptResult',
        ),
    ]
