# Generated by Django 3.1 on 2022-11-22 18:28

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viz', '0002_delete_optresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=200, verbose_name='job')),
                ('n_iter', models.IntegerField(verbose_name='n_iter')),
                ('optResult', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
    ]
