[a_size_shift.full_rmse.bayesian]
classification_truncation = 2
repair_truncation = 8
threshold = 1.111467711840768
repair_iter = 3
n_max_iter = 7

[a_size_shift.mae.bayesian]
classification_truncation = 2
repair_truncation = 7
threshold = 1.328659911028189
repair_iter = 3
n_max_iter = 2

[a_size_distortion.full_rmse.bayesian]
classification_truncation = 4
repair_truncation = 8
threshold = 2.41503160927556
repair_iter = 1
n_max_iter = 20

[a_size_outlier.full_rmse.bayesian]
classification_truncation = 3
repair_truncation = 8
threshold = 1.6770151791790129
repair_iter = 1
n_max_iter = 0

[cts_nbr_shift.mae.bayesian]
classification_truncation = 5
repair_truncation = 4
threshold = 1.1667373550680458
repair_iter = 2
n_max_iter = 20

[a_rate_shift.mae.bayesian]
classification_truncation = 3
repair_truncation = 7
threshold = 1.3065665903103703
repair_iter = 3
n_max_iter = 9

[ts_len_shift.mae.bayesian]
classification_truncation = 2
repair_truncation = 4
threshold = 1.400720874573094
repair_iter = 1
n_max_iter = 13
