[a_rate_shift.mae.grid]
smax = 1.0
smin = -1.0

[a_rate_shift.full_rmse.grid]
smax = 1.0
smin = -1.0

[a_rate_shift.partial_rmse.grid]
smax = 1.0
smin = -1.0

[a_rate_distortion.mae.grid]
smax = 1.0
smin = -1.0

[a_rate_distortion.full_rmse.grid]
smax = 1.0
smin = -1.0

[a_rate_distortion.partial_rmse.grid]
smax = 1.0
smin = -1.0

[a_rate_outlier.mae.grid]
smax = 1.0
smin = -1.0

[a_rate_outlier.full_rmse.grid]
smax = 1.0
smin = -1.0

[a_rate_outlier.partial_rmse.grid]
smax = 1.0
smin = -1.0
