[screen]
    name = "screen1"
    t = 1
    smin = -0.1
    smax  = 0.1


[screen]
    name = "screen01"
     t = 1
     smin = -0.01
     smax  = 0.01

[screen]
    name = "screen3"
    t = 1
    smin = -0.3
    smax  = 0.3

# cd , rpca params :
# classification_truncation
# repair_truncation
# threshold
# repair_iter
# n_max_iter
##
# imr params;
# p
# tau
# screen params;
# t
# smin
# smax