[rpca]
    threshold = 2
    classification_truncation = 2
    repair_truncation = 4
    n_max_iter = 10
    repair_iter = 1

[cdrec]
    classification_truncation = 2
    repair_truncation = 4
    threshold = 2
    n_max_iter = 10
    repair_iter = 3


[imr]
     p = 3
     tau = 0.01

[screen]
     t = 1
     smin = -0.2
     smax  = 0.2


# alg list ["rpca","screen","cdrec","imr"

# cd , rpca params :
# classification_truncation
# repair_truncation
# threshold
# repair_iter
# n_max_iter
##
# imr params;
# p
# tau
# screen params;
# t
# smin
# smax