[screen.screen1]
    t = 1
    smin = -0.1
    smax  = 0.1


[screen.screen01]
     t = 1
     smin = -0.01
     smax  = 0.01

[screen.screen02]
    t = 1
    smin = -0.3
    smax  = 0.3

[imr.imr01]
    tau = 0.1
    p = 5

[imr]
    tau = 0.01
    p = 5

[imr.imr2]
    tau = 0.001
    p = 5

[rpca]
    threshold = 2
    classification_truncation = 2
    repair_truncation = 4
    n_max_iter = 10
    repair_iter = 1

[rpca.rpcat2]
    threshold = 1
    classification_truncation = 3
    repair_truncation = 5
    n_max_iter = 10
    repair_iter = 4

[rpca.rpcamcorr]
    threshold = 1.5
    classification_truncation = 2
    repair_truncation = 5
    n_max_iter = 10
    repair_iter = 1
    sub_set = true


#[cdrec]
#    threshold = 1.5
#    classification_truncation = 2
#    repair_truncation = 5
#    n_max_iter = 10
#    repair_iter = 1

#[cdrec.cd1_3]
#    threshold = 1
#    classification_truncation = 3
#    repair_truncation = 5
#    n_max_iter = 10
#    repair_iter = 3

#[cdrec.cdrecmcorr]
#    threshold = 1.5
#    classification_truncation = 2
#    repair_truncation = 5
#    n_max_iter = 10
#    repair_iter = 1
#    sub_set = true

