version: '3'

services:
  web:
    volumes:
      - static:/RepairBenchWeb/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static:/RepairBenchWeb/static
    depends_on:
      - web
volumes:
  static:
