[rpca]
    threshold = 1.2
    classification_truncation = 2
    repair_truncation = 4
    n_max_iter = 50
    repair_iter = 1

[wrpca]
    threshold = 1.2
    classification_truncation = 2
    repair_truncation = 4
    n_max_iter = 50
    repair_iter = 1

[cdrec]
    classification_truncation = 2
    repair_truncation = 4
    threshold = 1.2
    n_max_iter = 2
    repair_iter = 10

[imr]
     p = 3
     tau = 0.001
     n_max_itr=100000

[screen] # use confidence intervall approach when smin and smax are not set
     t = 1


[screenglobal] # use percentile approach when smin and smax are not set
     t = 1



# cd , rpca params :
# classification_truncation
# repair_truncation
# threshold
# repair_iter
# n_max_iter
##
# imr params;
# p
# tau
# screen params;
# t
# smin
# smax

