[rpca]
    threshold = 0.8
    classification_truncation = 2
    repair_truncation = 4
    n_max_iter = 50
    repair_iter = 1

[cdrec]
    classification_truncation = 2
    repair_truncation = 4
    threshold = 0.8
    n_max_iter = 2
    repair_iter = 10

[imr]
     p = 1
     tau = 0.001

[screen]
     t = 1
     smax = 0.1
     smin = -0.1

