[rpca.rpca1]
    threshold = 5
    classification_truncation = -20
    repair_truncation = 4
    n_max_iter = 10
    repair_iter = 1


[rpca.rpca2]
    threshold = 20
    classification_truncation = -20
    repair_truncation = 40
    n_max_iter = 10
    repair_iter = 1


[rpca.rpca3]
    threshold = 2
    classification_truncation = 2
    repair_truncation = 4
    n_max_iter = 10
    repair_iter = 1
