[a_rate_shift.mae.grid]
p = 1
tau = 0.01

[a_rate_shift.full_rmse.grid]
p = 1
tau = 0.01

[a_rate_shift.partial_rmse.grid]
p = 1
tau = 0.01

[a_rate_distortion.mae.grid]
p = 1
tau = 0.005

[a_rate_distortion.full_rmse.grid]
p = 1
tau = 0.01

[a_rate_distortion.partial_rmse.grid]
p = 1
tau = 0.01

[a_rate_outlier.mae.grid]
p = 1
tau = 0.005

[a_rate_outlier.full_rmse.grid]
p = 1
tau = 0.01

[a_rate_outlier.partial_rmse.grid]
p = 1
tau = 0.01
