[a_size_shift.full_rmse.bayesian]
classification_truncation = 3
repair_truncation = 2
threshold = 1.1893579280429252
repair_iter = 2
n_max_iter = 20

[a_size_distortion.full_rmse.bayesian]
classification_truncation = 1
repair_truncation = 8
threshold = 1.8610355755865187
repair_iter = 2
n_max_iter = 6

[a_size_outlier.full_rmse.bayesian]
classification_truncation = 4
repair_truncation = 8
threshold = 1.495323902331126
repair_iter = 3
n_max_iter = 0
