[a_size_shift.mae.bayesian]
classification_truncation = 3
repair_truncation = 7
threshold = 2.3303821863388645
repair_iter = 4
n_max_iter = 19

[cts_nbr_shift.mae.bayesian]
classification_truncation = 3
repair_truncation = 8
threshold = 2.9337875383292986
repair_iter = 1
n_max_iter = 12

[a_rate_shift.mae.bayesian]
classification_truncation = 3
repair_truncation = 7
threshold = 2.9278741845402143
repair_iter = 4
n_max_iter = 18

[ts_len_shift.mae.bayesian]
classification_truncation = 1
repair_truncation = 8
threshold = 2.2592254882920617
repair_iter = 4
n_max_iter = 7
