[a_size_shift.mae.bayesian]
classification_truncation = 2
repair_truncation = 7
threshold = 1.328659911028189
repair_iter = 3
n_max_iter = 2

[cts_nbr_shift.mae.bayesian]
classification_truncation = 3
repair_truncation = 8
threshold = 1.4611710741207597
repair_iter = 3
n_max_iter = 11

[a_rate_shift.mae.bayesian]
classification_truncation = 3
repair_truncation = 7
threshold = 1.8674661448148433
repair_iter = 4
n_max_iter = 4

[ts_len_shift.mae.bayesian]
classification_truncation = 2
repair_truncation = 6
threshold = 1.496599000544066
repair_iter = 1
n_max_iter = 2
