version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/posgresql/data
    restart: always

  web:
    #image: exascalelab/repbench:v1 this is not there (yet)
    build: ../
    volumes:
      - static_volume:/usr/src/app/run/static
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=devsecretkey
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - PORT=8000 #todo check correct port for requests side was slow because of ports
    depends_on:
      - db
    command: >
      sh -c "python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py collectstatic --noinput &&
             gunicorn RepBenchWeb.wsgi:application --bind 0.0.0.0:8000 --access-logfile -"
    restart: always

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/run/static
    ports:
      - "12006:80"
    depends_on:
      - web
    restart: always


volumes:
  static_volume:
  pgdata:
