[a_rate_shift.mae.grid]
classification_truncation = 1
repair_truncation = 3
threshold = 2.5

[a_rate_shift.full_rmse.grid]
classification_truncation = 2
repair_truncation = 5
threshold = 2

[a_rate_shift.partial_rmse.grid]
classification_truncation = 2
repair_truncation = 5
threshold = 2

[a_rate_distortion.mae.grid]
classification_truncation = 1
repair_truncation = 3
threshold = 2.5

[a_rate_distortion.full_rmse.grid]
classification_truncation = 2
repair_truncation = 5
threshold = 2

[a_rate_distortion.partial_rmse.grid]
classification_truncation = 2
repair_truncation = 5
threshold = 2

[a_rate_outlier.mae.grid]
classification_truncation = 1
repair_truncation = 3
threshold = 2.5

[a_rate_outlier.full_rmse.grid]
classification_truncation = 2
repair_truncation = 5
threshold = 2

[a_rate_outlier.partial_rmse.grid]
classification_truncation = 2
repair_truncation = 5
threshold = 2
