from algorithms.Dimensionality_Reduction.RobustPCA.Robust_pca_estimator import Robust_PCA_estimator
from algorithms.Dimensionality_Reduction.CD.CDRecEstimator import CDRecEstimator
from algorithms.IMR.IMR_estimator import IMR_estimator
from algorithms.Screen.screen_estimator import SCREENEstimator
from algorithms.algorithm_mapper import algo_mapper

