["rpca"]
    "classification_truncation" = [1, 2, 3, 4, 5]
    "repair_truncation" = [1, 2, 3, 4, 5]
    "threshold" = [1, 1.2, 1.4, 1.8, 2]
    "repair_iter" = [1, 5, 10, 20]
    "n_max_iter" = [1, 5, 10, 20]

["cdrec"]
    "classification_truncation" = [1, 2, 3, 4, 5]
    "repair_truncation" = [1, 2, 3, 4, 5]
    "threshold" = [1, 1.2, 1.4, 1.8, 2]
    "repair_iter" = [1, 5, 10, 20]
    "n_max_iter" = [1, 5, 10, 20]

["screen"]
    "smin" = [-0.001, -0.01, -0.02, -0.5, -1, -2, -5]
    "smax" = [0.001, 0.01, 0.02, 0.5, 1, 2, 5]

["imr"]
    "p" = [1, 2, 3, 5, 10]
    "tau" = [0.0001, 0.005, 0.01, 0.05, 0.1, 1, 2]
