## config file for the repair algorithm names have to match repair/algorithms_config.py
[RPCA]
    threshold = 1.2
    classification_truncation = 2
    repair_truncation = 3
    n_max_iter = 10
    repair_iter = 10
    delta = 1


[CDREP]
    classification_truncation = 2
    repair_truncation = 3
    threshold = 1.2
    n_max_iter = 2
    repair_iter = 10
    delta = 1

[IMR]
    p = 3
    tau = 0.02
    n_max_itr = 20000

[SCREEN]
    t = 3
    smin = -0.1
    smax = +0.1
    #ci = [0.1,0.9] # use confidence intervall approach when smin and smax are not set


[screenglobal] # use percentile approach when smin and smax are not set
    t = 1
    ci = [0.1, 0.9] # use confidence intervall approach when smin and smax are not set


["SCREEN2"] # needs quotes because of the *
    t = 3
    smin = -0.1
    smax = +0.1
    amax = 0.1
    amin = -0.1


[SCR]
    THETA = 5
    delta = 1000



[KFilter]
    transition_cov = 0.5

