[rpca]
    threshold = 1.2
    classification_truncation = 2
    repair_truncation = 3
    n_max_iter = 10
    repair_iter = 10


[cdrec]
    classification_truncation = 2
    repair_truncation = 3
    threshold = 1.2
    n_max_iter = 2
    repair_iter = 10

[imr]
     p = 3
     tau = 0.02
     n_max_itr= 20000

[screen]
     t = 1
     ci = [0.1,0.9] # use confidence intervall approach when smin and smax are not set


[screenglobal] # use percentile approach when smin and smax are not set
     t = 1
     ci = [0.1,0.9] # use confidence intervall approach when smin and smax are not set



# cd , rpca params :
# classification_truncation
# repair_truncation
# threshold
# repair_iter
# n_max_iter
##
# imr params;
# p
# tau
# screen params;
# t
# smin
# smax

