[bafu.shift.full_rmse]
score = "0.15793301484956565"
time = 33.76211643218994
test_score = "0.04066835062344171"

[bafu.shift.partial_rmse]
score = "0.48035509712216956"
time = 28.922616243362427
test_score = "0.03619902978746038"

[bafu.distortion.full_rmse]
score = "0.15793301484956565"
time = 36.62820315361023
test_score = "0.04066835062344171"

[bafu.distortion.partial_rmse]
score = "0.48035509712216956"
time = 23.2017822265625
test_score = "0.03619902978746038"

[bafu.point.full_rmse]
score = "0.15793301484956565"
time = 27.85377597808838
test_score = "0.04066835062344171"

[bafu.point.partial_rmse]
score = "0.48035509712216956"
time = 38.04571199417114
test_score = "0.03619902978746038"

[msd1_5.shift.full_rmse]
score = "0.5517514201271418"
time = 38.88821816444397
test_score = "0.41502010134223466"

[msd1_5.shift.partial_rmse]
score = "1.1237513521382785"
time = 73.89755129814148
test_score = "1.135857487461053"

[msd1_5.distortion.full_rmse]
score = "0.5517514201271418"
time = 40.621031522750854
test_score = "0.41502010134223466"

[msd1_5.distortion.partial_rmse]
score = "1.1237513521382785"
time = 49.65991401672363
test_score = "1.135857487461053"

[msd1_5.point.full_rmse]
score = "0.5517514201271418"
time = 40.97792840003967
test_score = "0.41502010134223466"

[msd1_5.point.partial_rmse]
score = "1.1237513521382785"
time = 74.8399555683136
test_score = "1.135857487461053"

[bafu.shift.full_rmse.opt_params]
classification_truncation = "3"
repair_truncation = "5"
threshold = "1"
repair_iter = "1"
n_max_iter = "20"

[bafu.shift.partial_rmse.opt_params]
classification_truncation = "2"
repair_truncation = "5"
threshold = "1"
repair_iter = "1"
n_max_iter = "1"

[bafu.distortion.full_rmse.opt_params]
classification_truncation = "3"
repair_truncation = "5"
threshold = "1"
repair_iter = "1"
n_max_iter = "20"

[bafu.distortion.partial_rmse.opt_params]
classification_truncation = "2"
repair_truncation = "5"
threshold = "1"
repair_iter = "1"
n_max_iter = "1"

[bafu.point.full_rmse.opt_params]
classification_truncation = "3"
repair_truncation = "5"
threshold = "1"
repair_iter = "1"
n_max_iter = "20"

[bafu.point.partial_rmse.opt_params]
classification_truncation = "2"
repair_truncation = "5"
threshold = "1"
repair_iter = "1"
n_max_iter = "1"

[msd1_5.shift.full_rmse.opt_params]
classification_truncation = "3"
repair_truncation = "4"
threshold = "2"
repair_iter = "1"
n_max_iter = "15"

[msd1_5.shift.partial_rmse.opt_params]
classification_truncation = "2"
repair_truncation = "5"
threshold = "1"
repair_iter = "10"
n_max_iter = "7"

[msd1_5.distortion.full_rmse.opt_params]
classification_truncation = "3"
repair_truncation = "4"
threshold = "2"
repair_iter = "1"
n_max_iter = "15"

[msd1_5.distortion.partial_rmse.opt_params]
classification_truncation = "2"
repair_truncation = "5"
threshold = "1"
repair_iter = "10"
n_max_iter = "7"

[msd1_5.point.full_rmse.opt_params]
classification_truncation = "3"
repair_truncation = "4"
threshold = "2"
repair_iter = "1"
n_max_iter = "15"

[msd1_5.point.partial_rmse.opt_params]
classification_truncation = "2"
repair_truncation = "5"
threshold = "1"
repair_iter = "10"
n_max_iter = "7"
