["-2936934492606255097_a_size_shift_humidity.csv_bayesian_full_rmse"]
classification_truncation = 2
repair_truncation = 7
threshold = 2.252185329073071
repair_iter = 2
n_max_iter = 20

["2772177107633845425_a_size_shift_humidity.csv_bayesian_full_rmse"]
classification_truncation = 1
repair_truncation = 7
threshold = 2.3139669385490973
repair_iter = 4
n_max_iter = 12

["-2761032925636305918_a_size_distortion_humidity.csv_bayesian_full_rmse"]
classification_truncation = 2
repair_truncation = 6
threshold = 2.5405607716551635
repair_iter = 1
n_max_iter = 0

["-7449768854077025503_a_size_outlier_humidity.csv_bayesian_full_rmse"]
classification_truncation = 1
repair_truncation = 8
threshold = 3.2078082730959756
repair_iter = 5
n_max_iter = 20

["-6373102276175370470_a_size_distortion_humidity.csv_bayesian_full_rmse"]
classification_truncation = 1
repair_truncation = 7
threshold = 3.3032244836479965
repair_iter = 1
n_max_iter = 18

["-8581231982243173792_cts_nbr_shift_humidity.csv_bayesian_full_rmse"]
classification_truncation = 4
repair_truncation = 8
threshold = 2.0214658460926898
repair_iter = 3
n_max_iter = 6

["-8077930085981111270_cts_nbr_distortion_humidity.csv_bayesian_full_rmse"]
classification_truncation = 5
repair_truncation = 1
threshold = 4.599963970755111
repair_iter = 0
n_max_iter = 14

["3670846550473294504_cts_nbr_outlier_humidity.csv_bayesian_full_rmse"]
classification_truncation = 2
repair_truncation = 7
threshold = 2.6388198148685387
repair_iter = 3
n_max_iter = 4

["-7886820327948977732_a_rate_shift_humidity.csv_bayesian_full_rmse"]
classification_truncation = 1
repair_truncation = 8
threshold = 1.9852686113267095
repair_iter = 3
n_max_iter = 13

["7029009517541157568_a_size_shift_humidity.csv_bayesian_full_rmse"]
classification_truncation = 1
repair_truncation = 8
threshold = 2.3903281649410864
repair_iter = 1
n_max_iter = 5

["6274276458638875786_a_size_shift_humidity.csv_bayesian_full_rmse"]
classification_truncation = 1
repair_truncation = 8
threshold = 2.3903281649410864
repair_iter = 1
n_max_iter = 5

["-1170016997078493339_a_size_distortion_humidity.csv_bayesian_full_rmse"]
classification_truncation = 5
repair_truncation = 5
threshold = 3.9912950667936444
repair_iter = 2
n_max_iter = 4

["-148634596512278418_a_size_shift_humidity.csv_bayesian_full_rmse"]
classification_truncation = 1
repair_truncation = 8
threshold = 2.3903281649410864
repair_iter = 1
n_max_iter = 5

["-8109834095551003722_a_size_distortion_humidity.csv_bayesian_full_rmse"]
classification_truncation = 5
repair_truncation = 5
threshold = 3.9912950667936444
repair_iter = 2
n_max_iter = 4

["1902206178221775954_a_size_outlier_humidity.csv_bayesian_full_rmse"]
classification_truncation = 1
repair_truncation = 8
threshold = 3.0370694711684587
repair_iter = 5
n_max_iter = 4

["-7173168170304848400_a_size_outlier_humidity.csv_bayesian_full_rmse"]
classification_truncation = 1
repair_truncation = 8
threshold = 3.0370694711684587
repair_iter = 5
n_max_iter = 4

["-3094100352032021345_cts_nbr_shift_humidity.csv_bayesian_full_rmse"]
classification_truncation = 4
repair_truncation = 6
threshold = 1.816944668575299
repair_iter = 1
n_max_iter = 18

["4604525114758985588_a_size_distortion_humidity.csv_bayesian_full_rmse"]
classification_truncation = 5
repair_truncation = 5
threshold = 3.9912950667936444
repair_iter = 2
n_max_iter = 4

["-5192681429533675757_cts_nbr_shift_humidity.csv_bayesian_full_rmse"]
classification_truncation = 4
repair_truncation = 6
threshold = 1.816944668575299
repair_iter = 1
n_max_iter = 18

["-3132276781295662678_cts_nbr_distortion_humidity.csv_bayesian_full_rmse"]
classification_truncation = 5
repair_truncation = 8
threshold = 3.4590027222395325
repair_iter = 1
n_max_iter = 20

["7399970232874991160_cts_nbr_distortion_humidity.csv_bayesian_full_rmse"]
classification_truncation = 5
repair_truncation = 8
threshold = 3.4590027222395325
repair_iter = 1
n_max_iter = 20

["-4410319774165747470_a_size_outlier_humidity.csv_bayesian_full_rmse"]
classification_truncation = 1
repair_truncation = 8
threshold = 3.0370694711684587
repair_iter = 5
n_max_iter = 4

["7243407928673640780_cts_nbr_outlier_humidity.csv_bayesian_full_rmse"]
classification_truncation = 1
repair_truncation = 7
threshold = 1.9844535975987658
repair_iter = 3
n_max_iter = 2

["2365678202852426335_cts_nbr_outlier_humidity.csv_bayesian_full_rmse"]
classification_truncation = 1
repair_truncation = 7
threshold = 1.9844535975987658
repair_iter = 3
n_max_iter = 2

["1075932553111115239_a_rate_shift_humidity.csv_bayesian_full_rmse"]
classification_truncation = 2
repair_truncation = 8
threshold = 2.722620934217104
repair_iter = 2
n_max_iter = 0
