# Generated by Django 4.1.4 on 2023-02-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RepBenchWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='injectedcontainer',
            name='original_data_set',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
