# Generated by Django 4.1.7 on 2023-04-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RepBenchWeb', '0002_injectedcontainer_original_data_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='injectedcontainer',
            name='recommendation',
            field=models.JSONField(null=True),
        ),
    ]
