# Generated by Django 4.1.7 on 2023-05-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RepBenchWeb', '0004_dataset_granularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='injectedcontainer',
            name='granularity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
