# Generated by Django 4.2 on 2023-05-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RepBenchWeb', '0007_taskdata_celery_task_id_alter_taskdata_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdata',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='taskdata',
            name='task_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
