# Generated by Django 4.2 on 2023-05-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RepBenchWeb', '0008_taskdata_status_alter_taskdata_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdata',
            name='status',
            field=models.CharField(default='running', max_length=255),
        ),
    ]
