# Generated by Django 4.2 on 2023-05-16 11:09

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('RepBenchWeb', '0009_alter_taskdata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdata',
            name='autoML',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, null=True),
        ),
    ]
