[a_size_shift.full_rmse.bayesian]
classification_truncation = 2
repair_truncation = 8
threshold = 1.195450351750933
repair_iter = 5
n_max_iter = 1

[a_size_distortion.full_rmse.bayesian]
classification_truncation = 8
repair_truncation = 2
threshold = 5.0
repair_iter = 1
n_max_iter = 12

[a_size_outlier.full_rmse.bayesian]
classification_truncation = 3
repair_truncation = 8
threshold = 0.795877986167517
repair_iter = 3
n_max_iter = 1
